Update selector to support multiple selectors on a single page
equinor/webviz-ert pull request #125
Opened 2021-02-10 14:17 UTC by xjules

This PR provides support for multiple selectors on a single page.

2021-02-10 21:24 UTC, xjules commented
Screenshot:
![image](https://user-images.githubusercontent.com/6409506/107574252-c798cb00-6bee-11eb-9ea6-57f45013c2c1.png)

2021-02-12 16:10 UTC, oysteoh commented on ertviz/views/selector_view.py
> +                # style={"display": "block"},
could this be removed - or made more meaningful for others if it should stay as a future usage or something?

2021-02-12 16:23 UTC, oysteoh commented
I cannot get the toggling of the selection on/off to work - neither searching on keys. If i click manually and scroll it works as before.

2021-02-15 07:13 UTC, oysteoh requested changes
Make search case-insensitive and squash your commits - then i'll think we are good to go ! 👍

2021-02-15 13:43 UTC, oysteoh requested changes
Now it is also case-insensitive ! Great! Then please squash 👍 🚀

2021-02-16 13:43 UTC, oysteoh approved these changes

2021-02-16 13:45 UTC, merged